name: test

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: install mujs
        uses: ahaoboy/easy-setup@v1
        with:
          url: |-
            https://github.com/ahaoboy/mujs-build
            https://github.com/pnpm/pnpm
      - name: react
        run: |
          pnpm install
          pnpm run build:esbuild
          # pnpm run build:vite
          # pnpm run build:rsbuild
          # pnpm run build:rspack
          # pnpm run build:rollup
          # pnpm run build:rolldown


          mujs babel/index.js
      - name: zip
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          for dir in esbuild babel; do
            if [ -d "$dir" ]; then
              (cd "$dir" && zip -r "../${dir}.zip" .)
            else
              echo "Directory $dir does not exist, skipping zipping."
            fi
          done
      - name: release nightly
        uses: ncipollo/release-action@v1
        with:
          tag: "nightly"
          artifacts: "./*.zip"
          allowUpdates: true
          makeLatest: false
